### ISSUE TITLE
Threejs does not work on some types of PCs

### ISSUE THREAD

**Issue by fsdavid** [xgui3783/three-surfer#1]
Seems error is: `bundle.js:15 THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog invalid shaders THREE.WebGLShader: gl.getShaderInfoLog() vertex
ERROR: too many uniforms`

I'm attaching the log of the interactive viewer what is including the error
[atlases.ebrains.eu-1632301521239.log](https://github.com/xgui3783/three-surfer/files/7242087/atlases.ebrains.eu-1632301521239.log)

**Comment by xgui3783** [comment]
do you have hardware, OS, and browser used?

**Comment by fsdavid** [comment]
The bug was on windows and chrome (not on firefox) on Saras PC. But now seems it works on both browsers. So I'm closing the issue.
